'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceCliente
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceCliente.IClienteBusiness")>  _
    Public Interface IClienteBusiness
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteBusiness/GetClientes", ReplyAction:="http://tempuri.org/IClienteBusiness/GetClientesResponse")>  _
        Function GetClientes() As Entity.Cliente()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteBusiness/GetClientes", ReplyAction:="http://tempuri.org/IClienteBusiness/GetClientesResponse")>  _
        Function GetClientesAsync() As System.Threading.Tasks.Task(Of Entity.Cliente())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteBusiness/InsertCliente", ReplyAction:="http://tempuri.org/IClienteBusiness/InsertClienteResponse")>  _
        Function InsertCliente(ByVal cliente As Entity.Cliente) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteBusiness/InsertCliente", ReplyAction:="http://tempuri.org/IClienteBusiness/InsertClienteResponse")>  _
        Function InsertClienteAsync(ByVal cliente As Entity.Cliente) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteBusiness/UpdateCliente", ReplyAction:="http://tempuri.org/IClienteBusiness/UpdateClienteResponse")>  _
        Function UpdateCliente(ByVal cliente As Entity.Cliente) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteBusiness/UpdateCliente", ReplyAction:="http://tempuri.org/IClienteBusiness/UpdateClienteResponse")>  _
        Function UpdateClienteAsync(ByVal cliente As Entity.Cliente) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteBusiness/BuscarCliente", ReplyAction:="http://tempuri.org/IClienteBusiness/BuscarClienteResponse")>  _
        Function BuscarCliente(ByVal cliente As Entity.Cliente, ByVal campo As String, ByVal valor As String) As Entity.Cliente()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClienteBusiness/BuscarCliente", ReplyAction:="http://tempuri.org/IClienteBusiness/BuscarClienteResponse")>  _
        Function BuscarClienteAsync(ByVal cliente As Entity.Cliente, ByVal campo As String, ByVal valor As String) As System.Threading.Tasks.Task(Of Entity.Cliente())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IClienteBusinessChannel
        Inherits ServiceCliente.IClienteBusiness, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClienteBusinessClient
        Inherits System.ServiceModel.ClientBase(Of ServiceCliente.IClienteBusiness)
        Implements ServiceCliente.IClienteBusiness
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetClientes() As Entity.Cliente() Implements ServiceCliente.IClienteBusiness.GetClientes
            Return MyBase.Channel.GetClientes
        End Function
        
        Public Function GetClientesAsync() As System.Threading.Tasks.Task(Of Entity.Cliente()) Implements ServiceCliente.IClienteBusiness.GetClientesAsync
            Return MyBase.Channel.GetClientesAsync
        End Function
        
        Public Function InsertCliente(ByVal cliente As Entity.Cliente) As Integer Implements ServiceCliente.IClienteBusiness.InsertCliente
            Return MyBase.Channel.InsertCliente(cliente)
        End Function
        
        Public Function InsertClienteAsync(ByVal cliente As Entity.Cliente) As System.Threading.Tasks.Task(Of Integer) Implements ServiceCliente.IClienteBusiness.InsertClienteAsync
            Return MyBase.Channel.InsertClienteAsync(cliente)
        End Function
        
        Public Function UpdateCliente(ByVal cliente As Entity.Cliente) As Integer Implements ServiceCliente.IClienteBusiness.UpdateCliente
            Return MyBase.Channel.UpdateCliente(cliente)
        End Function
        
        Public Function UpdateClienteAsync(ByVal cliente As Entity.Cliente) As System.Threading.Tasks.Task(Of Integer) Implements ServiceCliente.IClienteBusiness.UpdateClienteAsync
            Return MyBase.Channel.UpdateClienteAsync(cliente)
        End Function
        
        Public Function BuscarCliente(ByVal cliente As Entity.Cliente, ByVal campo As String, ByVal valor As String) As Entity.Cliente() Implements ServiceCliente.IClienteBusiness.BuscarCliente
            Return MyBase.Channel.BuscarCliente(cliente, campo, valor)
        End Function
        
        Public Function BuscarClienteAsync(ByVal cliente As Entity.Cliente, ByVal campo As String, ByVal valor As String) As System.Threading.Tasks.Task(Of Entity.Cliente()) Implements ServiceCliente.IClienteBusiness.BuscarClienteAsync
            Return MyBase.Channel.BuscarClienteAsync(cliente, campo, valor)
        End Function
    End Class
End Namespace
