'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceUsuario
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceUsuario.IUsuarioBusiness")>  _
    Public Interface IUsuarioBusiness
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUsuarioBusiness/Loguear", ReplyAction:="http://tempuri.org/IUsuarioBusiness/LoguearResponse")>  _
        Function Loguear(ByVal usuario As Entity.Usuario) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUsuarioBusiness/Loguear", ReplyAction:="http://tempuri.org/IUsuarioBusiness/LoguearResponse")>  _
        Function LoguearAsync(ByVal usuario As Entity.Usuario) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IUsuarioBusinessChannel
        Inherits ServiceUsuario.IUsuarioBusiness, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UsuarioBusinessClient
        Inherits System.ServiceModel.ClientBase(Of ServiceUsuario.IUsuarioBusiness)
        Implements ServiceUsuario.IUsuarioBusiness
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Loguear(ByVal usuario As Entity.Usuario) As Boolean Implements ServiceUsuario.IUsuarioBusiness.Loguear
            Return MyBase.Channel.Loguear(usuario)
        End Function
        
        Public Function LoguearAsync(ByVal usuario As Entity.Usuario) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceUsuario.IUsuarioBusiness.LoguearAsync
            Return MyBase.Channel.LoguearAsync(usuario)
        End Function
    End Class
End Namespace
